name: Wash Sale Detector
input:
  file_name: "wash_sale_example.xlsx"
  sheets:
    - Sheet1
  columns:
    date: "Date"
    transaction: "Transaction"
    id: "Symbol"
    price: "Price"
output:
  file_name: "wash_sale_report.xlsx"
